name: the home depot java project

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: JAVA_HOME
    steps:
      - name: Checkout Java app repo
        uses: actions/checkout@v4

      - name: Setup Java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ vars.JAVA_HOME }}
          cache: 'maven'

      - name: Install dependencies
        run: mvn install

      - name: upload artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /home/runner/.m2/repository/com/example/java-demo-app/*

  deploy:
    name: deploy job
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact