name: the home depot java project

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  JAVA_HOME: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Java app repo
        uses: actions/checkout@v4

      - name: Setup Java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_HOME }}
          cache: 'maven'

      - name: Install dependencies
        run: mvn install
